"""
Server-side registry of real, tick-precise-validated marketplace strategy
configs (2026-08-29) - the counterpart to assets/marketplace-data.js's
MARKETPLACE_STRATEGIES on the frontend.

Origin: generated by strategy-lab's fast bar-based screen
(run_lab.py, 9840 strategies x 2 windows), then re-validated against real
MT5 tick data (tick_engine.py/validate_shortlist.py) - one of the original
6 picks (a EURUSD strategy) was DROPPED here because it flipped to a
negative return under tick-precise execution and was replaced. See
../strategy-lab/docs/HANDOFF.md for the full methodology, and the ATR bug
that was found and fixed the same day (materially changes these results
vs. anything generated before 2026-08-29).

Why this file exists (not just embedding the JSON in main.py or trusting
whatever the frontend sends): the marketplace download endpoints
(/api/marketplace/download/*) deliberately do NOT accept an arbitrary
client-supplied WorkspaceConfig the way /api/generate does - they only
ever generate one of THESE known-good, pre-approved configs, looked up by
id. This is what keeps the marketplace download path safe to leave
un-gated by _require_export_entitlement (see main.py) without opening an
"anyone can POST any config here for a free unlimited export" hole - a
client can only ever ask for one of the strategies below (current lineup plus
archived ones - see ARCHIVED_STRATEGY_IDS), never inject their own.

2026-08-31 update: the real purchase check landed - see
_require_strategy_ownership in main.py, which every /api/marketplace/
download/* endpoint now goes through. The free strategy stays fully
un-gated on purpose (see MARKETPLACE_STRATEGY_TIERS below); the other five
now 402 without a real, paid billing_events row (device_id- or, if logged
in, account-wide) - see supabase/schema.sql's "Marketplace strategy
purchases" section and db.has_purchased_strategy.

2026-09-19 update: the weekly rotation is now a script-driven process (see
../strategy-lab/apply_rotation.py and docs/HANDOFF.md's "Weekly rotation
checklist"). Rotated-out strategies stay in this file (tiers + configs) and are
listed in ARCHIVED_STRATEGY_IDS: owners keep downloading, nobody can buy them
any more. Never delete an id that has ever been sold.
"""
from __future__ import annotations

# Backend's own copy of which strategy_id is free / which Stripe price tier
# each paid one bills at - deliberately separate from (but must be kept in
# sync with) MARKETPLACE_STRATEGIES in assets/marketplace-data.js, same
# reasoning as strategy_config_id below: the frontend's copy is the display/
# catalog source of truth, this one is the BILLING source of truth, and a
# client must never be trusted to say "charge me the cheap tier" for the
# featured strategy. Whoever rotates the weekly lineup (editing both this
# file and marketplace-data.js) must update both:
#   "free"     - always downloadable, never goes through Stripe at all.
#   "featured" - the "Top performer this week" pick, $7.99
#                (STRIPE_PRICE_STRATEGY_FEATURED).
#   "standard" - every other paid strategy that week, $4.99
#                (STRIPE_PRICE_STRATEGY_STANDARD).
MARKETPLACE_STRATEGY_TIERS: dict[str, str] = {
    "usdjpy-prevclose-m15": "free",
    "xauusd-ma20-trend-m5": "featured",
    "xauusd-prevclose-m5": "standard",
    "usdcad-macross-m15": "standard",
    "usdcad-prevclose-m15": "standard",
    "audusd-prevclose-m15": "standard",
    "gbpusd-prevclose-fade-h1": "free",
    "usdjpy-macd-momentum-h1": "featured",
    "usdcad-ema50-trend-m15": "standard",
    "usdcad-ma20-trend-m30": "standard",
    "nzdusd-bollinger-fade-m5": "standard",
    "xauusd-ma20-short-m5": "standard",
}


# Strategies rotated out of the weekly lineup (2026-09-19). They stay in BOTH
# tables above/below on purpose: purchases are recorded per strategy_id, so an
# owner must still pass _require_strategy_ownership and still get a file from
# _marketplace_ir - removing an id here would 404 something a customer paid
# for. What "archived" changes is only that nobody can BUY it any more:
# billing.create_checkout_session refuses these ids (a hidden button on the
# frontend is not a gate - /api/billing/checkout/strategy is callable
# directly). Add an id here when it leaves the lineup; keep the matching
# `archived: true` in assets/marketplace-data.js in sync.
ARCHIVED_STRATEGY_IDS: frozenset[str] = frozenset({
    "audusd-prevclose-m15",
    "usdcad-macross-m15",
    "usdcad-prevclose-m15",
    "usdjpy-prevclose-m15",
    "xauusd-ma20-trend-m5",
    "xauusd-prevclose-m5",
})


def is_marketplace_strategy_archived(strategy_id: str) -> bool:
    return strategy_id in ARCHIVED_STRATEGY_IDS


def get_marketplace_strategy_tier(strategy_id: str) -> str | None:
    """None means "not a real marketplace strategy id" (404 territory) -
    distinct from any of the three real tier strings above."""
    return MARKETPLACE_STRATEGY_TIERS.get(strategy_id)


MARKETPLACE_STRATEGY_CONFIGS: dict = {
    "xauusd-prevclose-m5": {
        "rules": [{
            "asset": "XAUUSD", "timeframe": "PERIOD_M5",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 1.5}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 3.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "xauusd-ma20-trend-m5": {
        "rules": [{
            "asset": "XAUUSD", "timeframe": "PERIOD_M5",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "MA", "period": 20, "ma_type": "MODE_SMA"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "usdjpy-prevclose-m15": {
        "rules": [{
            "asset": "USDJPY", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "RISK_VALUE", "value": 20, "unit": "PIPS"},
                         "tp": {"kind": "RISK_VALUE", "value": 20, "unit": "PIPS"}}],
            "max_positions": 1,
        }],
    },
    "usdcad-prevclose-m15": {
        "rules": [{
            "asset": "USDCAD", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": "<", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "SELL", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 1.5}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 3.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "audusd-prevclose-m15": {
        "rules": [{
            "asset": "AUDUSD", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 1.5}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 3.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    # 2026-09-19 FIX: this entry used to be registered as "usdcad-ma50-trend-m15"
    # (price < EMA50) while the catalog (assets/marketplace-data.js), the tier
    # table above and every purchase used "usdcad-macross-m15" - so the id a
    # buyer owns had NO config here and every download of it 404'd ("Unknown
    # marketplace strategy id"). The pick was swapped on 2026-08-29 (commit
    # 70cac46) and only the frontend/tier table were updated. The config below
    # is what the catalog's own blockly_state has always shown and what the
    # tick-precise stats were measured on: SELL while EMA(10) < EMA(30).
    "usdcad-macross-m15": {
        "rules": [{
            "asset": "USDCAD", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "MA", "period": 10, "ma_type": "MODE_EMA"},
                          "operator": "<", "right": {"kind": "MA", "period": 30, "ma_type": "MODE_EMA"}},
            "actions": [{"direction": "SELL", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "gbpusd-prevclose-fade-h1": {
        "rules": [
            {
                "asset": "GBPUSD",
                "timeframe": "PERIOD_H1",
                "condition": {
                    "type": "comparison",
                    "left": {
                        "kind": "CANDLE",
                        "candle_type": "CURRENT"
                    },
                    "operator": ">",
                    "right": {
                        "kind": "CANDLE",
                        "candle_type": "PREV_CLOSE"
                    }
                },
                "actions": [
                    {
                        "direction": "SELL",
                        "lot": 0.1,
                        "sl": {
                            "kind": "RISK_VALUE",
                            "value": 20,
                            "unit": "PIPS"
                        },
                        "tp": {
                            "kind": "RISK_VALUE",
                            "value": 20,
                            "unit": "PIPS"
                        }
                    }
                ],
                "max_positions": 1
            }
        ]
    },
    "usdjpy-macd-momentum-h1": {
        "rules": [
            {
                "asset": "USDJPY",
                "timeframe": "PERIOD_H1",
                "condition": {
                    "type": "comparison",
                    "left": {
                        "kind": "MACD",
                        "line": "HIST"
                    },
                    "operator": ">",
                    "right": {
                        "kind": "NUMBER",
                        "value": 0
                    }
                },
                "actions": [
                    {
                        "direction": "BUY",
                        "lot": 0.1,
                        "sl": {
                            "kind": "RISK_VALUE",
                            "value": 15,
                            "unit": "PIPS"
                        },
                        "tp": {
                            "kind": "RISK_VALUE",
                            "value": 45,
                            "unit": "PIPS"
                        }
                    }
                ],
                "max_positions": 1
            }
        ]
    },
    "usdcad-ema50-trend-m15": {
        "rules": [
            {
                "asset": "USDCAD",
                "timeframe": "PERIOD_M15",
                "condition": {
                    "type": "comparison",
                    "left": {
                        "kind": "CANDLE",
                        "candle_type": "CURRENT"
                    },
                    "operator": ">",
                    "right": {
                        "kind": "MA",
                        "period": 50,
                        "ma_type": "MODE_EMA"
                    }
                },
                "actions": [
                    {
                        "direction": "BUY",
                        "lot": 0.1,
                        "sl": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 1.5
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        },
                        "tp": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 3.0
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        }
                    }
                ],
                "max_positions": 1
            }
        ]
    },
    "usdcad-ma20-trend-m30": {
        "rules": [
            {
                "asset": "USDCAD",
                "timeframe": "PERIOD_M30",
                "condition": {
                    "type": "comparison",
                    "left": {
                        "kind": "CANDLE",
                        "candle_type": "CURRENT"
                    },
                    "operator": ">",
                    "right": {
                        "kind": "MA",
                        "period": 20,
                        "ma_type": "MODE_SMA"
                    }
                },
                "actions": [
                    {
                        "direction": "BUY",
                        "lot": 0.1,
                        "sl": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 1.5
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        },
                        "tp": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 3.0
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        }
                    }
                ],
                "max_positions": 1
            }
        ]
    },
    "nzdusd-bollinger-fade-m5": {
        "rules": [
            {
                "asset": "NZDUSD",
                "timeframe": "PERIOD_M5",
                "condition": {
                    "type": "comparison",
                    "left": {
                        "kind": "CANDLE",
                        "candle_type": "CURRENT"
                    },
                    "operator": ">",
                    "right": {
                        "kind": "BANDS",
                        "period": 20,
                        "deviation": 2.5,
                        "band": "UPPER"
                    }
                },
                "actions": [
                    {
                        "direction": "SELL",
                        "lot": 0.1,
                        "sl": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 1.5
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        },
                        "tp": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 3.0
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        }
                    }
                ],
                "max_positions": 1
            }
        ]
    },
    "xauusd-ma20-short-m5": {
        "rules": [
            {
                "asset": "XAUUSD",
                "timeframe": "PERIOD_M5",
                "condition": {
                    "type": "comparison",
                    "left": {
                        "kind": "CANDLE",
                        "candle_type": "CURRENT"
                    },
                    "operator": "<",
                    "right": {
                        "kind": "MA",
                        "period": 20,
                        "ma_type": "MODE_SMA"
                    }
                },
                "actions": [
                    {
                        "direction": "SELL",
                        "lot": 0.1,
                        "sl": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 1.5
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        },
                        "tp": {
                            "kind": "MULTIPLY",
                            "left": {
                                "kind": "NUMBER",
                                "value": 3.0
                            },
                            "right": {
                                "kind": "ATR",
                                "period": 14
                            }
                        }
                    }
                ],
                "max_positions": 1
            }
        ]
    },
}


def get_marketplace_strategy_config(strategy_id: str) -> dict | None:
    return MARKETPLACE_STRATEGY_CONFIGS.get(strategy_id)
