"""
Server-side registry of real, tick-precise-validated marketplace strategy
configs (2026-08-29) - the counterpart to assets/marketplace-data.js's
MARKETPLACE_STRATEGIES on the frontend.

Origin: generated by strategy-lab's fast bar-based screen
(run_lab.py, 9840 strategies x 2 windows), then re-validated against real
MT5 tick data (tick_engine.py/validate_shortlist.py) - one of the original
6 picks (a EURUSD strategy) was DROPPED here because it flipped to a
negative return under tick-precise execution and was replaced. See
../strategy-lab/docs/HANDOFF.md for the full methodology, and the ATR bug
that was found and fixed the same day (materially changes these results
vs. anything generated before 2026-08-29).

Why this file exists (not just embedding the JSON in main.py or trusting
whatever the frontend sends): the marketplace download endpoints
(/api/marketplace/download/*) deliberately do NOT accept an arbitrary
client-supplied WorkspaceConfig the way /api/generate does - they only
ever generate one of THESE known-good, pre-approved configs, looked up by
id. This is what keeps the marketplace download path safe to leave
un-gated by _require_export_entitlement (see main.py) without opening an
"anyone can POST any config here for a free unlimited export" hole - a
client can only ever ask for one of the 6 strategies below, never inject
their own.

STAGING-ONLY STATE (2026-08-29): downloads here are intentionally NOT
gated by the entitlement/billing system yet - real Stripe-backed
marketplace purchases (and real per-strategy pricing) are a deliberate,
separate follow-up the user is doing themselves on main. Do not treat the
un-gated download endpoints as production-ready as-is once Stripe pricing
exists - they'll need a real "has this device actually purchased this
strategy" check added at that point, in the same spot _require_export_entitlement
lives.
"""
from __future__ import annotations

MARKETPLACE_STRATEGY_CONFIGS: dict = {
    "xauusd-prevclose-m5": {
        "rules": [{
            "asset": "XAUUSD", "timeframe": "PERIOD_M5",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 1.5}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 3.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "xauusd-ma20-trend-m5": {
        "rules": [{
            "asset": "XAUUSD", "timeframe": "PERIOD_M5",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "MA", "period": 20, "ma_type": "MODE_SMA"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "usdjpy-prevclose-m15": {
        "rules": [{
            "asset": "USDJPY", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "RISK_VALUE", "value": 20, "unit": "PIPS"},
                         "tp": {"kind": "RISK_VALUE", "value": 20, "unit": "PIPS"}}],
            "max_positions": 1,
        }],
    },
    "usdcad-prevclose-m15": {
        "rules": [{
            "asset": "USDCAD", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": "<", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "SELL", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 1.5}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 3.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "audusd-prevclose-m15": {
        "rules": [{
            "asset": "AUDUSD", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": ">", "right": {"kind": "CANDLE", "candle_type": "PREV_CLOSE"}},
            "actions": [{"direction": "BUY", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 1.5}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 3.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
    "usdcad-ma50-trend-m15": {
        "rules": [{
            "asset": "USDCAD", "timeframe": "PERIOD_M15",
            "condition": {"type": "comparison", "left": {"kind": "CANDLE", "candle_type": "CURRENT"},
                          "operator": "<", "right": {"kind": "MA", "period": 50, "ma_type": "MODE_EMA"}},
            "actions": [{"direction": "SELL", "lot": 0.1,
                         "sl": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}},
                         "tp": {"kind": "MULTIPLY", "left": {"kind": "NUMBER", "value": 2.0}, "right": {"kind": "ATR", "period": 14}}}],
            "max_positions": 1,
        }],
    },
}


def get_marketplace_strategy_config(strategy_id: str) -> dict | None:
    return MARKETPLACE_STRATEGY_CONFIGS.get(strategy_id)
