// -----------------------------------------------------------------
// AlgoPuzzleBot.cs
// Auto-generated by "AlgoPuzzle" (No-Code Builder)
// Generated: 2026-08-14 12:22 UTC
//
// WARNING: Always test on a Demo account before going live.
// -----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using cAlgo.API;
using cAlgo.API.Indicators;
using cAlgo.API.Internals;

namespace cAlgo.Robots
{
    [Robot(TimeZone = TimeZones.UTC, AccessRights = AccessRights.None)]
    public class AlgoPuzzleBot : Robot
    {
        // Per-rule strategy configuration (from the visual block builder) -
        // each rule uses its own _tradeSymbolN/_tradeBarsN explicitly
        // (never the Robot's own Symbol/Bars/MarketSeries, which are tied
        // to whatever chart this cBot is attached to), so every rule always
        // trades the asset chosen for it in the builder, regardless of
        // which chart the cBot happens to be running on. Same design
        // intent as the MT5 export's TradeSymbol.
        private static readonly string[] TradeSymbolBaseName = new string[] { "EURUSD" };
        private readonly string[] TradeSymbolName = new string[1];
        private readonly Symbol[] _tradeSymbol = new Symbol[1];
        private readonly Bars[] _tradeBars = new Bars[1];

        // How many separate "rounds" of THEN actions are currently open per
        // rule, and each rule's own configured limit (the "Positions" field on
        // its IF block). Resets to 0 once every position THAT RULE opened has
        // actually closed (see OnPositionsClosed below), so the next signal can
        // open up to MaxSimultaneousPositions[i] rounds again for that rule.
        private readonly int[] _roundsSinceFlat = new int[1];
        private static readonly int[] MaxSimultaneousPositions = new int[] { 1 };

        // Per-position virtual Stop Loss / Take Profit state, keyed by
        // cAlgo's own Position.Id. Unlike MQL5, ExecuteMarketOrder() hands
        // this back directly (TradeResult.Position.Id) - no separate
        // lookup needed. On a Netted account, cAlgo itself merges
        // same-symbol orders into one position and returns the SAME id for
        // each round - even across TWO DIFFERENT rules that happen to
        // share a symbol, since cAlgo does not distinguish by Label for
        // this - so RegisterVirtualStop() below blends them exactly like
        // the MT5 export does for netting accounts (see its comment). This
        // works correctly for both Hedged and Netted Account.AccountType
        // without needing to branch on it explicitly.
        private class VirtualStopState
        {
            public Symbol Symbol = null!;
            public int RuleIndex;
            public double ExitRef;
            public double Volume;
            public double SL;
            public double TP;
            public int Direction; // 1 = Buy, -1 = Sell
        }
        private readonly Dictionary<long, VirtualStopState> _trackedStops = new Dictionary<long, VirtualStopState>();

        // Indicator handles
        private RelativeStrengthIndex _rsi0 = null!;

        protected override void OnStart()
        {
            Positions.Closed += OnPositionsClosed;

            // --- Rule 1 (EURUSD) ---
            {
                // TradeSymbolBaseName[0] may not exist as-is on this broker.
                // ResolveBrokerSymbol() tries an exact match first, then falls
                // back to scanning for a close match - same shape as the MT5
                // export's ResolveBrokerSymbol(). It is NOT confirmed whether
                // cTrader brokers append suffixes the way some MT5 white-labels
                // do - this fallback is cheap insurance either way, but treat it
                // as unverified until checked against a real cTrader account.
                TradeSymbolName[0] = ResolveBrokerSymbol(TradeSymbolBaseName[0]);
                if (TradeSymbolName[0] == null)
                {
                    Print("Rule 1: no symbol matching \"{0}\" was found on this broker. Check the Symbol list for the exact name this broker uses and edit TradeSymbolBaseName near the top of this file.", TradeSymbolBaseName[0]);
                    Stop();
                    return;
                }
                _tradeSymbol[0] = Symbols.GetSymbol(TradeSymbolName[0]);
                _tradeBars[0] = MarketData.GetBars(TimeFrame.Weekly, TradeSymbolName[0]);
                _tradeBars[0].BarOpened += OnTradeBarOpened0;
            _rsi0 = Indicators.RelativeStrengthIndex(_tradeBars[0].ClosePrices, 14);
                Print("AlgoPuzzle cBot - Rule 1 initialized on {0}", TradeSymbolName[0]);
            }

        }

        // Resolves the broker's actual symbol name for a base asset name -
        // see the comment on TradeSymbolBaseName above for why this exists
        // and its verification status.
        private string? ResolveBrokerSymbol(string baseName)
        {
            if (Symbols.Exists(baseName))
                return baseName;

            foreach (var candidate in Symbols)
            {
                if (candidate.IndexOf(baseName, StringComparison.OrdinalIgnoreCase) >= 0 && Symbols.Exists(candidate))
                {
                    Print("Exact symbol \"{0}\" not found on this broker - using \"{1}\" instead (closest match).", baseName, candidate);
                    return candidate;
                }
            }
            return null;
        }

        // Snaps a price to the symbol's tradeable tick size - same purpose
        // as the MT5 export's NormalizeToTick().
        private double NormalizeToTick(Symbol symbol, double price)
        {
            double tickSize = symbol.TickSize;
            if (tickSize <= 0)
                tickSize = symbol.PipSize / 10.0;
            double snapped = Math.Round(price / tickSize) * tickSize;
            return Math.Round(snapped, symbol.Digits);
        }

        // Counts how many currently-tracked positions belong to one rule -
        // used to reset that rule's own "rounds since flat" counter
        // independently of every other rule.
        private int CountTrackedForRule(int ruleIndex)
        {
            return _trackedStops.Values.Count(s => s.RuleIndex == ruleIndex);
        }

        // Registers a just-opened (or just-added-to) position's virtual
        // SL/TP, blending this round's exit-side reference price into the
        // running volume-weighted average for that position id first - a
        // direct port of the MT5 export's RegisterVirtualStop() (see its
        // comment there for the full reasoning on why the blend matters
        // and why it's NOT anchored to the entry-side price). `symbol` and
        // `ruleIndex` are stored so OnTick() checks the right symbol's
        // price and so each rule can count only its own positions.
        private void RegisterVirtualStop(long positionId, Symbol symbol, int ruleIndex, double exitRefPrice, double slDistance, double tpDistance, int direction, double volume)
        {
            VirtualStopState state;
            if (!_trackedStops.TryGetValue(positionId, out state))
            {
                state = new VirtualStopState { Symbol = symbol, RuleIndex = ruleIndex, ExitRef = 0, Volume = 0 };
                _trackedStops[positionId] = state;
            }

            double totalVolume = state.Volume + volume;
            double blendedExitRef = totalVolume > 0
                ? (state.ExitRef * state.Volume + exitRefPrice * volume) / totalVolume
                : exitRefPrice;

            state.ExitRef = blendedExitRef;
            state.Volume = totalVolume;
            state.Direction = direction;
            state.SL = slDistance <= 0 ? 0 : NormalizeToTick(symbol, direction == 1 ? blendedExitRef - slDistance : blendedExitRef + slDistance);
            state.TP = tpDistance <= 0 ? 0 : NormalizeToTick(symbol, direction == 1 ? blendedExitRef + tpDistance : blendedExitRef - tpDistance);
        }

        // Cleans up tracked state for a position that closed by any means
        // (our own virtual stop below, a manual close, a margin call, ...),
        // and resets THAT position's own rule's round counter once nothing
        // of its is left open - independent of every other rule.
        private void OnPositionsClosed(PositionClosedEventArgs args)
        {
            VirtualStopState closedState;
            if (_trackedStops.TryGetValue(args.Position.Id, out closedState))
            {
                int ruleIndex = closedState.RuleIndex;
                _trackedStops.Remove(args.Position.Id);
                if (CountTrackedForRule(ruleIndex) == 0)
                {
                    _roundsSinceFlat[ruleIndex] = 0;
                }
            }
        }

        protected override void OnTick()
        {
            // Virtual Stop Loss / Take Profit monitor: runs on EVERY tick
            // (not gated to new bars), since price can cross a stop level
            // at any moment. Never attaches SL/TP to the order itself -
            // watches live price and closes the position directly, exactly
            // like the MT5 export (see its OnTick() for the full reasoning).
            // Shared across every rule below - state.Symbol (not a single
            // field) is used for the price check, since different rules
            // can track positions on different symbols.
            foreach (var kvp in _trackedStops.ToList())
            {
                long positionId = kvp.Key;
                var state = kvp.Value;
                var position = Positions.FirstOrDefault(p => p.Id == positionId);
                if (position == null)
                {
                    _trackedStops.Remove(positionId);
                    continue;
                }

                double checkPrice = state.Direction == 1 ? state.Symbol.Bid : state.Symbol.Ask;
                bool hitSL = state.SL > 0 && (state.Direction == 1 ? checkPrice <= state.SL : checkPrice >= state.SL);
                bool hitTP = state.TP > 0 && (state.Direction == 1 ? checkPrice >= state.TP : checkPrice <= state.TP);

                if (hitSL || hitTP)
                {
                    var closeResult = ClosePosition(position);
                    if (closeResult.IsSuccessful)
                    {
                        Print(hitSL ? "Virtual Stop Loss triggered - position closed." : "Virtual Take Profit triggered - position closed.");
                    }
                    else
                    {
                        Print("Virtual SL/TP close failed: {0}", closeResult.Error);
                    }
                }
            }
        }

        // Strategy logic for Rule 1 only evaluates once per new bar on
        // its own configured timeframe - cAlgo's Bars.BarOpened event does
        // this natively, unlike MQL5 which has to compare iTime() by hand
        // every tick. Each rule subscribes its own instance of this handler
        // to its own _tradeBars[0], so rules on different timeframes each fire
        // only on their own bar closes.
        private void OnTradeBarOpened0(BarOpenedEventArgs obj)
        {
            bool signalTriggered0 = ((_rsi0.Result.LastValue) < (30.0));

            if (signalTriggered0)
            {
                // "Positions" setting from the IF block - same round-based
                // gate as the MT5 export, scoped to this rule only.
                if (_roundsSinceFlat[0] < MaxSimultaneousPositions[0])
                {
                    _roundsSinceFlat[0]++;
                // Action 1: Open BUY
                {
                    // Lot from the builder is a target - converted to cAlgo's
                    // volume-in-units and snapped to this broker's actual step/min/max.
                    double lotToTrade = _tradeSymbol[0].NormalizeVolumeInUnits(_tradeSymbol[0].QuantityToVolumeInUnits(0.1), RoundingMode.ToNearest);
                    double entryPrice = _tradeSymbol[0].Ask;
                    double exitRefPrice = _tradeSymbol[0].Bid;
                    double slDistance = (30.0 * _tradeSymbol[0].PipSize);
                    double tpDistance = (90.0 * _tradeSymbol[0].PipSize);
                    // Same virtual SL/TP design as the MT5 export (see RegisterVirtualStop
                    // above): never attached to the order itself, watched every tick
                    // instead, so behaviour stays identical across both export targets.
                    // The label (last param) tags this position as belonging to THIS
                    // rule - cAlgo's equivalent of a magic number - so it's never
                    // confused with another rule's positions, even on the same symbol.
                    var result = ExecuteMarketOrder(TradeType.Buy, TradeSymbolName[0], lotToTrade, "AlgoPuzzle_Rule0");
                    if (!result.IsSuccessful)
                    {
                        Print("BUY order failed: {0}", result.Error);
                    }
                    else
                    {
                        RegisterVirtualStop(result.Position.Id, _tradeSymbol[0], 0, exitRefPrice, slDistance, tpDistance, 1, lotToTrade);
                    }
                }
                }
            }
        }

    }
}
